[{index: 0, data: "Achievers University, Owo"},
{index: 1, data: "Adeleke University, Ede"},
{index: 2, data: "Afe Babalola University, Ado-Ekiti"},
{index: 3, data: "African University of Science & Technology"},
{index: 4, data: "Ajayi Crowther University, Ibadan"},
{index: 5, data: "Al-Hikmah University, Ilorin"},
{index: 6, data: "Al-Qalam University"},
{index: 7, data: "American University of Nigeria, Yola"},
{index: 8, data: "Augustine University"},
{index: 9, data: "Babcock University,Ilishan-Remo"},
{index: 10, data: "Baze University"},
{index: 11, data: "Bells University of Technology, Otta"},
{index: 12, data: "Benson Idahosa University, Benin City"},
{index: 13, data: "Bingham University, New Karu"},
{index: 14, data: "Bowen University, Iwo"},
{index: 15, data: "Caleb University, Lagos"},
{index: 16, data: "Caritas University"},
{index: 17, data: "CETEP City University"},
{index: 18, data: "Chrisland University"},
{index: 19, data: "Christopher University Mowe"},
{index: 20, data: "Covenant University Ota"},
{index: 21, data: "Crawford University Igbesa"},
{index: 22, data: "Crescent University"},
{index: 23, data: "Edwin Clark University, KaIgbodo"},
{index: 24, data: "Elizade University, Ilara-Mokin"},
{index: 25, data: "Evangel University, Akaeze"},
{index: 26, data: "Fountain Unveristy, Oshogbo"},
{index: 27, data: "Godfrey Okoye University, Ugwuomu-Nike"},
{index: 28, data: "Gregory University, Uturu"},
{index: 29, data: "Hallmark University"},
{index: 30, data: "Hezekiah University, Umudi"},
{index: 31, data: "Igbinedion University Okada"},
{index: 32, data: "Joseph Ayo Babalola University, Ikeji-Arakeji"},
{index: 33, data: "Kings University"},
{index: 34, data: "Kwararafa University, Wukari"},
{index: 35, data: "Landmark University, Omu-Aran."},
{index: 36, data: "Lead City University, Ibadan"},
{index: 37, data: "Madonna University, Okija"},
{index: 38, data: "Mcpherson University, Seriki Sotayo, Ajebo"},
{index: 39, data: "Micheal & Cecilia University"},
{index: 40, data: "Mountain Top University"},
{index: 41, data: "Nigerian-Turkish Nile University"},
{index: 42, data: "Novena University, Ogume"},
{index: 43, data: "Obong University, Obong Ntak"},
{index: 44, data: "Oduduwa University, Ipetumodu"},
{index: 45, data: "Pan-Atlantic University, Lagos"},
{index: 46, data: "Paul University, Awka"},
{index: 47, data: "Redeemer's University, Mowe"},
{index: 48, data: "Renaissance University"},
{index: 49, data: "Rhema University, Obeama-Asa"},
{index: 50, data: "Ritman University"},
{index: 51, data: "Salem University, Lokoja"},
{index: 52, data: "Samuel Adegboyega University, Ogwa."},
{index: 53, data: "Southwestern University, Oku Owa"},
{index: 54, data: "Summit University"},
{index: 55, data: "Tansian University, Umunya"},
{index: 56, data: "University of Mkar, Mkar"},
{index: 57, data: "Veritas University"},
{index: 58, data: "Wellspring University, Evbuobanosa"},
{index: 59, data: "Wesley University. of Science & Technology, Ondo"},
{index: 60, data: "Western Delta University, Oghara"},
{index: 61, data: "Federal Universities"},
{index: 62, data: "Abubakar Tafawa Balewa University, Bauchi"},
{index: 63, data: "Ahmadu Bello University, Zaria"},
{index: 64, data: "Bayero University, Kano"},
{index: 65, data: "Federal University Gashua"},
{index: 66, data: "Federal University of Agriculture, Abeokuta"},
{index: 67, data: "Federal University of Petroleum Resources, Effurun"},
{index: 68, data: "Federal University of Technology, Akure"},
{index: 69, data: "Federal University of Technology, Minna"},
{index: 70, data: "Federal University of Technology, Owerri"},
{index: 71, data: "Federal University, Birnin Kebbi"},
{index: 72, data: "Federal University, Dutse."},
{index: 73, data: "Federal University, Dutsin-Ma."},
{index: 74, data: "Federal University, Gusau"},
{index: 75, data: "Federal University, Kashere,"},
{index: 76, data: "Federal University, Lafia."},
{index: 77, data: "Federal University, Lokoja."},
{index: 78, data: "Federal University, Ndifu-Alike."},
{index: 79, data: "Federal University, Otuoke,"},
{index: 80, data: "Federal University, Oye-Ekiti."},
{index: 81, data: "Federal University, Wukari."},
{index: 82, data: "Michael Okpara University of Agriculture, Umudike"},
{index: 83, data: "Modibbo Adama University of Technology, Yola"},
{index: 84, data: "National Open University of Nigeria."},
{index: 85, data: "Nigeria Police Academy Wudil"},
{index: 86, data: "Nigerian Defence Academy"},
{index: 87, data: "University of Ilorin"},
{index: 88, data: "Nnamdi Azikiwe University, Awka"},
{index: 89, data: "Obafemi Awolowo University,Ile-Ife"},
{index: 90, data: "University of Abuja, Gwagwalada"},
{index: 91, data: "University of Agriculture, Makurdi"},
{index: 92, data: "University of Benin"},
{index: 93, data: "University of Calabar"},
{index: 94, data: "University of Ibadan"},
{index: 95, data: "University of Jos"},
{index: 96, data: "University of Lagos"},
{index: 97, data: "University of Maiduguri"},
{index: 98, data: "University of Nigeria, Nsukka"},
{index: 99, data: "University of Port-Harcourt"},
{index: 100, data: "University of Uyo"},
{index: 101, data: "Usumanu Danfodiyo University"},
{index: 102, data: "State Universities"},
{index: 103, data: "Abia State University, Uturu"},
{index: 104, data: "Adamawa State University Mubi"},
{index: 105, data: "Adekunle Ajasin University, Akungba"},
{index: 106, data: "Akwa Ibom State University of Technology, Uyo"},
{index: 107, data: "Ambrose Alli University, Ekpoma"},
{index: 108, data: "Bauchi State University, Gadau"},
{index: 109, data: "Benue State University, Makurdi"},
{index: 110, data: "Bukar Abba Ibrahim University, Damaturu"},
{index: 111, data: "Chukwuemeka Odumegwu Ojukwu University, Uli"},
{index: 112, data: "Cross River State University of Science &Technology, Calabar"},
{index: 113, data: "Delta State University Abraka"},
{index: 114, data: "Eastern Palm University Ogboko, Imo State"},
{index: 115, data: "Ebonyi State University, Abakaliki"},
{index: 116, data: "Edo University Iyamo"},
{index: 117, data: "Ekiti State University"},
{index: 118, data: "Enugu State University of Science and Technology."},
{index: 119, data: "Gombe State Univeristy"},
{index: 120, data: "Ibrahim Badamasi Babangida University, Lapai"},
{index: 121, data: "Ignatius Ajuru University of Education,Rumuolumeni"},
{index: 122, data: "Imo State University, Owerri"},
{index: 123, data: "Kaduna State University"},
{index: 124, data: "Kano University of Science & Technology, Wudil"},
{index: 125, data: "Kebbi State University,"},
{index: 126, data: "Kogi State University Anyigba"},
{index: 127, data: "Kwara State University, Ilorin"},
{index: 128, data: "Ladoke Akintola University of Technology, Ogbomoso"},
{index: 129, data: "Lagos State University, Ojo"},
{index: 130, data: "Nasarawa State University Keffi"},
{index: 131, data: "Niger Delta University Yenagoa"},
{index: 132, data: "Northwest University Kano"},
{index: 133, data: "Olabisi Onabanjo University, Ago Iwoye"},
{index: 134, data: "Ondo State University of Medical Sciences"},
{index: 135, data: "Ondo State University of Science and Technology Okitipupa"},
{index: 136, data: "Osun State University Osogbo"},
{index: 137, data: "Oyo State Technical University Ibadan"},
{index: 138, data: "Plateau State University Bokkos"},
{index: 139, data: "River State University of Science and Technology"},
{index: 140, data: "Sokoto State University"},
{index: 141, data: "Sule Lamido University, Kafin Hausa, Jigawa"},
{index: 142, data: "Tai Solarin University of Education Ijebu Ode"},
{index: 143, data: "Taraba State University, Jalingo"},
{index: 144, data: "Umar Musa Yar' Adua University Katsina"},
{index: 145, data: "All Polytechnics in Nigeria"},
{index: 146, data: "Abdu Gusau Polytechnic Talata Mafa"},
{index: 147, data: "Abia State Polytechnic"},
{index: 148, data: "Abraham Adesanya Polytechnic"},
{index: 149, data: "Abubakar Tatari Ali Polytechnic"},
{index: 150, data: "Adamawa State Polytechnic"},
{index: 151, data: "Adegbenro ICT Polytechnic"},
{index: 152, data: "Ajayi Polytechnic"},
{index: 153, data: "Akanu Ibiam Federal Polytechnic Unwana"},
{index: 154, data: "Akwa Ibom State Polytechnic"},
{index: 155, data: "Allover Central Polytechnic"},
{index: 156, data: "Auchi Polytechnic"},
{index: 157, data: "Bauchi Institute of Arabic & Islamic-Studies"},
{index: 158, data: "Benue State Polytechnic"},
{index: 159, data: "Best Solution Polytechnic"},
{index: 160, data: "Bolmor Polytechnic"},
{index: 161, data: "Calvary Polytechnic"},
{index: 162, data: "Covenant Polytechnic"},
{index: 163, data: "Cross-River State Institute of Technology And Management"},
{index: 164, data: "Crown Polytechnic"},
{index: 165, data: "Delta State Polytechnic Otefe Oghara"},
{index: 166, data: "Delta State Polytechnic Ogwashi-Uku"},
{index: 167, data: "Delta State Polytechnic Ozoro"},
{index: 168, data: "Dorben Polytechnic"},
{index: 169, data: "Eastern Polytechnic"},
{index: 170, data: "Edo State Institute of Technology Management"},
{index: 171, data: "Federal Polytechnic Ile-Oluji"},
{index: 172, data: "Federal Polytechnic Ado-Ekiti"},
{index: 173, data: "Federal Polytechnic Bali"},
{index: 174, data: "Federal Polytechnic Bauchi"},
{index: 175, data: "Federal Polytechnic Bida"},
{index: 176, data: "Federal Polytechnic Damaturu"},
{index: 177, data: "Federal Polytechnic Ede"},
{index: 178, data: "Federal Polytechnic Ekowe"},
{index: 179, data: "Federal Polytechnic Idah"},
{index: 180, data: "Federal Polytechnic Ilaro"},
{index: 181, data: "Federal Polytechnic Ile Oluji"},
{index: 182, data: "Federal Polytechnic Kaura Namoda"},
{index: 183, data: "Federal Polytechnic Mubi"},
{index: 184, data: "Federal Polytechnic Nasarawa"},
{index: 185, data: "Federal Polytechnic Nekede"},
{index: 186, data: "Federal Polytechnic Offa"},
{index: 187, data: "Federal Polytechnic of Oil and Gas Bonny"},
{index: 188, data: "Federal Polytechnic Oko"},
{index: 189, data: "Federal-Polytechnic-Ukana"},
{index: 190, data: "Fidei Polytechnic"},
{index: 191, data: "Gateway Polytechnic Saapade"},
{index: 192, data: "Gboko Polytechnic"},
{index: 193, data: "Global Polytechnic"},
{index: 194, data: "Grace Polytechnic"},
{index: 195, data: "Hassan Usman Katsina Polytechnic"},
{index: 196, data: "Heritage Polytechnic"},
{index: 197, data: "Hussaini Adamu Federal Polytechnic"},
{index: 198, data: "Ibadan City Polytechnic"},
{index: 199, data: "Ibarapa Polytechnic Eruwa"},
{index: 200, data: "Igbajo Polytechnic"},
{index: 201, data: "Imo State Polytechnic Umuagwo"},
{index: 202, data: "Institute of Management Technology, Enugu"},
{index: 203, data: "Interlink Polytechnic"},
{index: 204, data: "Jigawa State Polytechnic Dutse"},
{index: 205, data: "Kaduna Polytechnic"},
{index: 206, data: "Kalac Christal Polytechnic"},
{index: 207, data: "Kano State Polytechnic"},
{index: 208, data: "Ken Sarowiwa Polytechnic"},
{index: 209, data: "Kings Polytechnic"},
{index: 210, data: "Umar Musa Yar' Adua University Katsina"},
{index: 211, data: "Kwara State Polytechnic"},
{index: 212, data: "Lagos City Polytechnic"},
{index: 213, data: "Lagos State Polytechnic Ikorodu"},
{index: 214, data: "Lens Polytechnic"},
{index: 215, data: "Lighthouse Polytechnic"},
{index: 216, data: "Mai Idris Alooma Polytechnic Geidam"},
{index: 217, data: "Marist Polytechnic"},
{index: 218, data: "Moshood Abiola Polytechnic"},
{index: 219, data: "Nacabs Polytechnic"},
{index: 220, data: "Nasarawa State Polytechnic"},
{index: 221, data: "National Institute of Construction Technology"},
{index: 222, data: "Nigerian Army Institute of Technology and Environmental Studies"},
{index: 223, data: "Niger State Polytechnic"},
{index: 224, data: "Nogak Polytechnic"},
{index: 225, data: "Nuhu Bamalli Polytechnic"},
{index: 226, data: "Ogun State Institute of Technology"},
{index: 227, data: "Oke Ogun Polytechnic"},
{index: 228, data: "Umar Musa Yar' Adua University Katsina"},
{index: 229, data: "Osun State Polytechnic"},
{index: 230, data: "Petroleum Training Institute"},
{index: 231, data: "Umar Musa Yar' Adua University Katsina"},
{index: 232, data: "Umar Musa Yar' Adua University Katsina"},
{index: 233, data: "Polytechnic Imesi-Ile"},
{index: 234, data: "Polytechnic Otada-Adoka"},
{index: 235, data: "Port Harcourt Polytechnic"},
{index: 236, data: "Prime Polytechnic"},
{index: 237, data: "Ramat Polytechnic"},
{index: 238, data: "Ronik Polytechnic"},
{index: 239, data: "Rufus-Giwa-Polytechnic"},
{index: 240, data: "Shaka Polytechnic"},
{index: 241, data: "St. Mary Polytechnic"},
{index: 242, data: "Sure Foundation Polytechnic"},
{index: 243, data: "Temple Gate Polytechnic"},
{index: 244, data: "The Polytechnic gbo Owu"},
{index: 245, data: "The Polytechnic Ibadan"},
{index: 246, data: "Tower Polytechnic"},
{index: 247, data: "Trinity Polytechnic"},
{index: 248, data: "Umaru-Ali-Shinkafi-Polytechnic"},
{index: 249, data: "Uma Ukpai Polytechnic"},
{index: 250, data: "Uyo City Polytechnic"},
{index: 251, data: "Valley View Polytechnic"},
{index: 252, data: "Waziri Umaru Federal Polytechnic"},
{index: 253, data: "Yaba College of Technology"},
{index: 254, data: "Colleges of Education in Nigeria"},
{index: 255, data: "Adamawa State College of Education"},
{index: 256, data: "Adamu Augie College of Education"},
{index: 257, data: "Adeniran Ogunsanya College of Education"},
{index: 258, data: "Adeyemi College of Education"},
{index: 259, data: "African Thinkers Community of Inquiry"},
{index: 260, data: "Airforce Institute of Technology"},
{index: 261, data: "Akwa-Ibom State College of Art & Science"},
{index: 262, data: "Akwa-Ibom State College of Education"},
{index: 263, data: "Ansar Ud Deen College of Education"},
{index: 264, data: "Bayelsa State College of Arts and Science"},
{index: 265, data: "City College of Education"},
{index: 266, data: "College of Education Gashua"},
{index: 267, data: "College of Education katsina-Ala"},
{index: 268, data: "College-of-Education-Arochukwu"},
{index: 269, data: "College of Education Azare"},
{index: 270, data: "College of Education Ekiadolor Benin"},
{index: 271, data: "College of Education Gindiri"},
{index: 272, data: "College of Education Ikere-Ekiti"},
{index: 273, data: "College of Education Ila Orangun"},
{index: 274, data: "college of education ilemona"},
{index: 275, data: "College of Education Jalingo"},
{index: 276, data: "College of Education Lafiagi"},
{index: 277, data: "College of Education Nsukka"},
{index: 278, data: "College of Education Waka BIU"},
{index: 279, data: "College of Education Warri"},
{index: 280, data: "College of Education Zuba"},
{index: 281, data: "College of Technology osun"},
{index: 282, data: "Corner Stone College of Education"},
{index: 283, data: "Cross-River State College of Education"},
{index: 284, data: "Delar College of Education"},
{index: 285, data: "Delta State College of Education"},
{index: 286, data: "Delta State Coll of Physical Education"},
{index: 287, data: "Ebonyi State College of Education"},
{index: 288, data: "Edo State College of Education"},
{index: 289, data: "Emmanuel Alayande College of Education"},
{index: 290, data: "Enugu State College of Education"},
{index: 291, data: "Federal College of Education"},
{index: 292, data: "Federal College of Education Abeokuta"},
{index: 293, data: "Federal College of Education Akoka"},
{index: 294, data: "Federal College of Education Asaba"},
{index: 295, data: "Federal College of Education Bichi"},
{index: 296, data: "Federal College of Education Eha Amufu"},
{index: 297, data: "Federal College of Education Gombe"},
{index: 298, data: "Federal College of Education Gusau"},
{index: 299, data: "Federal College of Education Kano"},
{index: 300, data: "Federal College of Education Katsina"},
{index: 301, data: "Federal College of Education Kontagora"},
{index: 302, data: "Federal College of Education Obudu"},
{index: 303, data: "Federal College of Education Okene"},
{index: 304, data: "Federal College of Education Omoku"},
{index: 305, data: "Federal College of Education Oyo"},
{index: 306, data: "Federal College of Education Pankshin"},
{index: 307, data: "Federal College of Education Potiskum"},
{index: 308, data: "Federal College of Education Yola"},
{index: 309, data: "Federal College of Education Zaria"},
{index: 310, data: "Havard Wilson College of Education"},
{index: 311, data: "Institute of Ecumenical Education"},
{index: 312, data: "Isaac Jasper Boro"},
{index: 313, data: "Isa Kaita College of Education"},
{index: 314, data: "Jamaatu College of Education"},
{index: 315, data: "Jigawa State College of Education"},
{index: 316, data: "Kaduna State College of Education"},
{index: 317, data: "Kashim Ibrahim College of Education"},
{index: 318, data: "Kogi State College of Education"},
{index: 319, data: "Kwara State College of Education"},
{index: 320, data: "lvan Ikoku College of Education"},
{index: 321, data: "Michael Otedola Coll of Prim Education"},
{index: 322, data: "Muftau Olanihun College of Education"},
{index: 323, data: "Muhyideen College of Education"},
{index: 324, data: "Nasarrawa State College of Education"},
{index: 325, data: "Nigerian Army School of Education"},
{index: 326, data: "Niger State College of Education"},
{index: 327, data: "Nwafor Orizu College of Education"},
{index: 328, data: "Osisatech College of Education"},
{index: 329, data: "Osun State College of Education"},
{index: 330, data: "Peaceland College of Education"},
{index: 331, data: "Rivers College of Education"},
{index: 332, data: "Saadatu Rimi College of Education"},
{index: 333, data: "Shehu shagari College of Education"},
{index: 334, data: "St Augustine College of Education"},
{index: 335, data: "Tai Solarin College of Education"},
{index: 336, data: "Umar Ibn Ibrahim El Kanemi College of Education"},
{index: 337, data: "Zamfara State College of Education"}]